# Staging Environment Values
# Moderate resources for staging testing

image:
  repository: scalecraft/dagctl-dbt-operator
  tag: "0.1.0"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

leaderElection:
  enabled: true
