{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dagctl-dbt.serviceAccountName" . }}
  labels:
    {{- include "dagctl-dbt.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dagctl-dbt.fullname" . }}-manager-role
  labels:
    {{- include "dagctl-dbt.labels" . | nindent 4 }}
rules:
- apiGroups:
  - orchestration.scalecraft.io
  resources:
  - dbtprojects
  - dbtruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.scalecraft.io
  resources:
  - dbtprojects/status
  - dbtruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dagctl-dbt.fullname" . }}-manager-rolebinding
  labels:
    {{- include "dagctl-dbt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dagctl-dbt.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "dagctl-dbt.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
